server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/heklo/spring_clou_configuration.git
          default-label: master
  application:
    name: configServer
